name: Run maven test on push

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v2

    - name: 2. Run maven test
      uses: xlui/action-maven-cli@master
      with:
        lifecycle: 'clean package test'
